//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicShopManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReviews
    {
        public int ReviewID { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public string ReviewDescription { get; set; }
        public decimal Rating { get; set; }
        public int ProductID { get; set; }
        public string ReviewerName { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
