//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicShopManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderHistory()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public int OrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string ReceiptNumber { get; set; }
        public int EmployeeID { get; set; }
        public int CustomerID { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public byte Status { get; set; }
        public string CurrencyCode { get; set; }
    
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual Users Users { get; set; }
    }
}
